"""empty message

Revision ID: 05e621a23473
Revises: e3a81477f915
Create Date: 2024-02-02 18:14:51.001505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e621a23473'
down_revision = 'e3a81477f915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_species', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'species', ['id_species'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_species')

    # ### end Alembic commands ###
