"""empty message

Revision ID: a438cb6800db
Revises: 05e621a23473
Create Date: 2024-02-02 18:20:36.042543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a438cb6800db'
down_revision = '05e621a23473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['id_people'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_people')

    # ### end Alembic commands ###
